site_name: Docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
repo_url: https://github.com/KSMC-TS/docs
extra_css:
    - stylesheets/extra.css
plugins:
    - search
use_directory_urls: false
nav:
    - Home: 'index.md'
    - 'Fortinet':
        - 'Automated Certificate Renewal': 'fortinet/AutomatedCertificateRenewal/index.md'
    - 'Intune':
        - 'Create App Deployment Msi': 'intune/CreateAppDeploymentMsi/index.md'
    - 'Wordpress':
        - 'Send Gravity Forms Submissions to Excel': 'wordpress/SendGravityFormsSubmissionstoExcel/index.md'